---
title: "How Socioeconomic Factors Affect Average Age of First Birth in Canada"

author: 
  - Sevnur Kulak
  - Dongqi Bi
  - Ivan Li
thanks: "Code and data are available at: https://github.com/hellowoshibb/Age_of_First_Birth_Analysis"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "write abstract here"
output: 
  bookdown::pdf_document2:
    fig_caption: yes
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hash)
library(dplyr)
library(forcats)
library(knitr)
library(janitor)
library(tidyverse)
library(tidyr)
library(wrapr)
library(haven)
library(ggplot2)
library(gridExtra)
```



# Introduction


# Data

```{r, message=FALSE, cache=TRUE, warning = FALSE, echo = FALSE}
#read gss raw data
gss <- read_csv(here::here("input/data/gss.csv"))
```

```{r, age-first-child, fig.cap="Distribution of age at which respondents have their first child ",warning=FALSE, echo=FALSE, results='hide',fig.keep='all', message=FALSE}

gss_afb <- gss |>
  select(age_at_first_birth, sex) |>
  na.omit()


gss_afb |>
  ggplot(mapping = aes(x = age_at_first_birth))+
  geom_histogram(fill="steelblue3", colour = "white", aes(y = (..count..)/sum(..count..)))+
  labs(x = "Age at first birth",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")+
  theme_classic()

```



```{r, female-age-first-child, fig.cap="Distribution of age at which respondents have their first child by gender ", warning=FALSE, echo=FALSE,results='hide',fig.keep='all', message=FALSE}

gss_afb <- gss |>
  select(age_at_first_birth, sex) |>
  na.omit()

p1 <- gss_afb |>
  filter(sex == "Female") |>
  ggplot(mapping = aes(x = age_at_first_birth))+
  geom_histogram(aes(y = (..count..)/sum(..count..)), fill="steelblue3", colour = "white")+
  labs(x = "Age at first birth (Female)",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")+
  theme(plot.title = element_text(size=10))+
  theme_classic()


  
p2 <- gss_afb |>
  filter(sex == "Male") |>
  ggplot(mapping = aes(x = age_at_first_birth))+
  geom_histogram(aes(y = (..count..)/sum(..count..)), fill="steelblue3", colour = "white")+
  labs(x = "Age at first birth (Male)",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")+
  theme(plot.title = element_text(size=10))+
  theme_classic()

cowplot::plot_grid(p1, p2)

```

```{r, education, fig.cap="Distribution of age at which respondents have their first child by education levels ", warning=FALSE, echo=FALSE,results='hide',fig.keep='all',, message=FALSE}

ed <- gss |>
  select(age_at_first_birth, education)|>
  filter(education == "High school diploma or a high school equivalency certificate" |
         education == "Less than high school diploma or its equivalent" |
         education == "Bachelor's degree (e.g. B.A., B.Sc., LL.B.)"|
        education == "University certificate, diploma or degree above the bach...")
  
ed[ed == "High school diploma or a high school equivalency certificate"] <- "High School"
ed[ed == "Less than high school diploma or its equivalent"] <- "Less than high school"
ed[ed == "Bachelor's degree (e.g. B.A., B.Sc., LL.B.)"] <- "Bachelor"
ed[ed == "University certificate, diploma or degree above the bach..."] <- "Above Bachelor"

ed |>
  ggplot(mapping = aes(x = age_at_first_birth, fill=education))+
  geom_histogram(aes(y = (..count..)/sum(..count..)),colour = "white")+
  labs(x = "Age at first birth",
       y = "Counts of respondents",
       fill = "Education levels")+
  scale_fill_manual(values = c("steelblue1","steelblue2", "steelblue3", "steelblue4"))+
  theme_classic()
```




```{r, income, fig.cap="Part1 : Distribution of age at which respondents have their first child by occupation and income", fig.height=20, warning=FALSE, echo=FALSE,results='hide',fig.keep='all', message=FALSE}

oc <- gss |>
  select(age_at_first_birth, occupation, income_respondent)|>
  filter(occupation == "Business, finance, and administration occupations" |
         occupation == "Sales and service occupations" |
         occupation == "Health occupations"|
         occupation == "Management occupations")
  
oc[oc == "Business, finance, and administration occupations"] <- "Business occupation"
oc[oc == "Sales and service occupations"] <- "Sales occupation"
oc[oc == "Management occupations"] <- "Management occupations"


p1 = oc %>% mutate(income_respondent = fct_relevel(income_respondent, 
            "Less than $25,000", "$25,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999","$100,000 to $ 124,999", "$125,000 and more" )) |> filter(occupation == "Health occupations") |>  ggplot(aes(x=income_respondent, y=age_at_first_birth)) +
  geom_boxplot(colour = 'green4')+  geom_jitter(alpha = 0.3, width = 0.05, height = 0, colour = 'green4')+
  labs(title = "Health Occupation Distribution" ,,
       color = "Occupation")+
  theme(axis.text.x = element_text(angle = 35)) + labs(x='Income', y='Age at First Birth')

p2 = oc %>% mutate(income_respondent = fct_relevel(income_respondent, 
            "Less than $25,000", "$25,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999","$100,000 to $ 124,999", "$125,000 and more" )) |> filter(occupation == "Business occupation") |>  ggplot(aes(x=income_respondent, y=age_at_first_birth)) +
  geom_boxplot(colour = 'gold3')+  geom_jitter(alpha = 0.3, width = 0.05, height = 0, colour = 'gold3')+
  labs(title = "Business Occupation Distribution" ,,
       color = "Occupation")+
  theme(axis.text.x = element_text(angle = 35)) + labs(x='Income', y='Age at First Birth')

p3 = oc %>% mutate(income_respondent = fct_relevel(income_respondent, 
            "Less than $25,000", "$25,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999","$100,000 to $ 124,999", "$125,000 and more" )) |> filter(occupation == "Sales occupation") |>  ggplot(aes(x=income_respondent, y=age_at_first_birth)) +
  geom_boxplot(colour = 'blue')+  geom_jitter(alpha = 0.3, width = 0.05, height = 0, colour = 'blue')+
  labs(title = "Sales Occupation Distribution" ,,
       color = "Occupation")+
  theme(axis.text.x = element_text(angle = 35)) + labs(x='Income', y='Age at First Birth')

p4 = oc %>% mutate(income_respondent = fct_relevel(income_respondent, 
            "Less than $25,000", "$25,000 to $49,999", "$50,000 to $74,999", "$75,000 to $99,999","$100,000 to $ 124,999", "$125,000 and more" )) |> filter(occupation == "Management occupations") |>  ggplot(aes(x=income_respondent, y=age_at_first_birth)) +
  geom_boxplot(colour = 'red')+  geom_jitter(alpha=0.3, width = 0.05, height = 0, colour = 'red')+
  labs(title = "Management Occupation Distribution" ,,
       color = "Occupation")+
  theme(axis.text.x = element_text(angle = 35)) + labs(x='Income', y='Age at First Birth')

cowplot::plot_grid(p1, p2, nrow=2)

```

```{r, income2, fig.cap="Part2 : Distribution of age at which respondents have their first child by occupation and income", fig.height=20, warning=FALSE, echo=FALSE,results='hide',fig.keep='all', message=FALSE}
cowplot::plot_grid(p3, p4, nrow=2)
```


```{r, feelings, fig.cap="Age at which having their first child vs feelings about life as a whole", warning=FALSE, echo=FALSE, results='hide',fig.keep='all', message=FALSE}


gss_fl <- gss%>%
  select(feelings_life, age_at_first_birth) %>%
  na.omit()%>%
  group_by(feelings_life) %>%
  mutate(mean = mean(age_at_first_birth))%>%
  rename(mean_age = `mean`)



gss_fl %>%
 ggplot(aes(x=feelings_life, y=age_at_first_birth)) +
   geom_point(size = 0.05, color = "steelblue1")+
  geom_line(aes(x = feelings_life, y = mean_age), size = 1)+
  labs(x = "Satisfaction with life scale", y = "Age at first birth")
  theme_classic()


```




# Results


# Discussion


# Survey


# References


# Appendix
