---
title: "Write title here"

author: 
  - Sevnur Kulak
  - Dongqi Bi
thanks: "Code and data are available at: https://github.com/hellowoshibb/STA304_paper3"
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "write abstract here"
output: 
  bookdown::pdf_document2:
    fig_caption: yes
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(hash)
library(dplyr)
library(forcats)
library(knitr)
library(janitor)
library(tidyverse)
library(tidyr)
library(wrapr)
library(haven)
library(ggplot2)
library(gridExtra)
```

```{r, message=FALSE, cache=TRUE, warning = FALSE, echo = FALSE}
#read gss raw data
gss <- read_csv(here::here("input/data/gss.csv"))
```

```{r, age-first-child, fig.cap="Age of respondents having first child ", warning=FALSE, echo=FALSE}

gss_afb <- gss |>
  select(age_at_first_birth, sex) |>
  na.omit()

gss_afb |>
  ggplot(mapping = aes(x = age_at_first_birth, fill=(..count..)/sum(..count..)))+
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  labs(title = "Distribution of Age of Respondents having their First Child",
       x = "Age",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")

```



```{r, female-age-first-child, fig.cap="Distribution of Age of Females having their first child ", warning=FALSE, echo=FALSE}

gss_afb <- gss |>
  select(age_at_first_birth, sex) |>
  na.omit()

#gss_afb |>
  #ggplot(mapping = aes(x = age_at_first_birth, fill = sex))+
  #geom_bar()+
  #labs(x = "Age of Respondents having their first child",
       #y = "Number of respondents",
       #fill = "Gender")

gss_afb |>
  filter(sex == "Female") |>
  ggplot(mapping = aes(x = age_at_first_birth, fill=(..count..)/sum(..count..)))+
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  labs(title = "Distribution of Age of Females having their First Child",
       x = "Age",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")



```

```{r, Male-age-first-child, fig.cap="Distribution of Age of Males having their first child ", warning=FALSE, echo=FALSE}

  
gss_afb |>
  filter(sex == "Male") |>
  ggplot(mapping = aes(x = age_at_first_birth, fill=(..count..)/sum(..count..)))+
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  labs(title = "Distribution of Age of Males having their first child" ,
       x = "Age",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")

```

```{r, edu-highschooldropout-age-first-child, fig.cap="Distribution of Age of High School Dropouts having their first child ", warning=FALSE, echo=FALSE}

gss |>
  filter(education == "Less than high school diploma or its equivalent") |>
  ggplot(mapping = aes(x = age_at_first_birth, fill=(..count..)/sum(..count..)))+
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  labs(title = "Distribution of Age of High School Dropouts having their first child" ,
       x = "Age",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")
```

```{r, edu-highschool-diploma-age-first-child, fig.cap="Distribution of Age of High School Graduates having their first child", warning=FALSE, echo=FALSE}

gss |>
  filter(education == "High school diploma or a high school equivalency certificate") |>
  ggplot(mapping = aes(x = age_at_first_birth, fill=(..count..)/sum(..count..)))+
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  labs(title = "Distribution of Age of High School Graduates having their first child" ,
       x = "Age",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")
```

```{r, edu-bachelors-age-first-child, fig.cap="Distribution of Age of Bachelor Degree Receipients having their first child ", warning=FALSE, echo=FALSE}

gss |>
  filter(education == "Bachelor's degree (e.g. B.A., B.Sc., LL.B.)") |>
  ggplot(mapping = aes(x = age_at_first_birth, fill=(..count..)/sum(..count..)))+
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  labs(title = "Distribution of Bachelor Degree Receipients having their first child" ,
       x = "Age",
       y = "Proportion of respondents",
       fill = "Proportion of respondents")
```